import { Alert, Button, Card, Col, Flex, Progress, Row, Space, Statistic, Tabs } from '@sue/design-web-react';
import { ChevronRight, Plus, Sparkles } from 'lucide-react';
import { PageHeader, PriorityTag, StateTag } from '../../shared/components';
import type { DrawerState, Goal, Habit, Task } from '../../shared/types';
import styles from './index.module.css';

type Props = { goals: Goal[]; tasks: Task[]; habits: Habit[]; selectedGoal: string; setSelectedGoal: (id: string) => void; setDrawer: (drawer: DrawerState) => void; onOpenAiDecomposition: () => void };
export function GoalsPage({ goals, tasks, habits, selectedGoal, setSelectedGoal, setDrawer, onOpenAiDecomposition }: Props) {
  const current = goals.find((goal) => goal.id === selectedGoal) || goals[0];
  const children = goals.filter((goal) => goal.parentId === current.id); const relatedTasks = tasks.filter((task) => task.goalId === current.id); const relatedHabits = habits.filter((habit) => habit.goalIds.includes(current.id));
  const renderTree = (parentId?: string, depth = 0): React.ReactNode => goals.filter((goal) => goal.parentId === parentId).map((goal) => <div data-product-wiki="goal-structure" key={goal.id} className={styles.treeItem} style={{ paddingLeft: depth * 16 }}><Button type="text" className={selectedGoal === goal.id ? styles.treeActive : ''} onClick={() => setSelectedGoal(goal.id)} icon={<ChevronRight size={14} />}>{goal.title}</Button>{renderTree(goal.id, depth + 1)}</div>);
  return <><PageHeader wikiId="goal-overview" title="目标管理" detail="目标是执行实体的约束源，所有变更都会即时校验层级规则。" action={<div data-product-wiki="goal-interaction"><Space><Button icon={<Sparkles size={15} />} onClick={onOpenAiDecomposition}>AI 拆解此目标</Button><Button type="primary" icon={<Plus size={15} />} onClick={() => setDrawer({ kind: 'goal' })}>新建目标</Button></Space></div>} />
    <Row gutter={[16, 16]} align="top"><Col xs={24} lg={8}><div data-product-wiki="goal-structure"><Card title="目标树" extra={<Button type="text" size="small" icon={<Plus size={15} />} aria-label="新建目标" onClick={() => setDrawer({ kind: 'goal' })} />}>{renderTree()}</Card></div></Col><Col xs={24} lg={16}><div data-product-wiki="goal-overview"><Card title={current.title} extra={<div data-product-wiki="goal-interaction"><Space><Button onClick={() => setDrawer({ kind: 'goal', id: current.id })}>编辑</Button><Button type="primary" icon={<Sparkles size={15} />} onClick={onOpenAiDecomposition}>AI 拆解</Button></Space></div>}><Flex vertical gap={16}><div data-product-wiki="goal-rules"><Space><StateTag status={current.status} /><PriorityTag importance={current.importance} /></Space></div><p className={styles.goalDescription}>{current.description}</p><div data-product-wiki="goal-rules"><Row gutter={[16, 16]}><Col span={8}><Statistic title="当前进度" value={current.progress} suffix="%" /></Col><Col span={8}><Statistic title="关联任务" value={relatedTasks.length} suffix="项" /></Col><Col span={8}><Statistic title="关联习惯" value={relatedHabits.length} suffix="项" /></Col></Row><Progress percent={current.progress} /></div><div data-product-wiki="goal-structure"><Tabs items={[{ key: 'children', label: `子目标 ${children.length}`, children: <RelationList items={children} empty="暂无子目标" /> }, { key: 'tasks', label: `关联任务 ${relatedTasks.length}`, children: <RelationList items={relatedTasks} empty="暂无关联任务" /> }, { key: 'habits', label: `关联习惯 ${relatedHabits.length}`, children: <RelationList items={relatedHabits} empty="暂无关联习惯" /> }, { key: 'history', label: '历史记录', children: <div className={styles.history}>{current.history.map((item) => <p key={item}>{item}</p>)}</div> }]} /></div></Flex></Card></div></Col></Row></>;
}
function RelationList({ items, empty }: { items: Array<{ id: string; title: string; status?: string }>; empty: string }) { return items.length ? <div className={styles.relationList}>{items.map((item) => <Flex justify="space-between" align="center" key={item.id}><b>{item.title}</b>{item.status && <StateTag status={item.status} />}</Flex>)}</div> : <Alert type="info" showIcon title={empty} />; }
