import { useState } from 'react';
import type { Dispatch, SetStateAction } from 'react';
import { Alert, Button, Card, Checkbox, Col, Flex, Modal, Row, Select, Space, Statistic, Switch, Table, Tabs, Tag } from '@sue/design-web-react';
import { Plus } from 'lucide-react';
import { PageHeader, PriorityTag, StateTag } from '../../shared/components';
import { productRef } from '../../product-wiki';
import { TODAY } from '../../shared/mock-data';
import type { DrawerState, Goal, RecurringTodoTemplate, Task, Todo, TodoStatus } from '../../shared/types';
import { goalName, repeatLabel, statusLabel } from '../../shared/utils';
import styles from './index.module.css';

type Props = { todos: Todo[]; goals: Goal[]; tasks: Task[]; templates: RecurringTodoTemplate[]; setDrawer: (drawer: DrawerState) => void; updateTodo: (id: string, patch: Partial<Todo>, event?: string) => void; completeTodo: (todo: Todo) => void; setTemplates: Dispatch<SetStateAction<RecurringTodoTemplate[]>> };
export function TodosPage({ todos, goals, tasks, templates, setDrawer, completeTodo, setTemplates }: Props) {
  const [tab, setTab] = useState('today'); const [filter, setFilter] = useState<TodoStatus | 'all'>('all'); const [selected, setSelected] = useState<string[]>([]); const [batchOpen, setBatchOpen] = useState(false);
  const visible = todos.filter((todo) => (filter === 'all' || todo.status === filter) && (tab !== 'today' || todo.planned <= TODAY || todo.due < TODAY));
  const columns = [{ title: '', render: (_: unknown, todo: Todo) => <span data-product-ref={productRef('growth.todo.interaction')}><Checkbox checked={selected.includes(todo.id)} onChange={(event) => setSelected((items) => event.target.checked ? [...items, todo.id] : items.filter((id) => id !== todo.id))} /></span> }, { title: '待办', render: (_: unknown, todo: Todo) => <span data-product-ref={productRef('growth.todo.interaction')}><Button type="link" onClick={() => setDrawer({ kind: 'todo', id: todo.id })}>{todo.title}{todo.recurrenceId && <Tag color="purple" className={styles.inlineTag}>周期</Tag>}</Button></span> }, { title: '关联', render: (_: unknown, todo: Todo) => <span data-product-ref={productRef('growth.todo.priority')}>{todo.taskId ? tasks.find((task) => task.id === todo.taskId)?.title : goalName(goals, todo.goalId)}</span> }, { title: '时间', render: (_: unknown, todo: Todo) => <span data-product-ref={productRef('growth.todo.priority')}>{`${todo.planned} - ${todo.due}`}</span> }, { title: '优先级', render: (_: unknown, todo: Todo) => <span data-product-ref={productRef('growth.todo.priority')}><PriorityTag importance={todo.importance} urgency={todo.urgency} /></span> }, { title: '状态', render: (_: unknown, todo: Todo) => <div data-product-ref={productRef('growth.todo.interaction')}><Space><StateTag status={todo.status} />{todo.status !== 'done' && <Button size="small" onClick={() => completeTodo(todo)}>完成</Button>}</Space></div> }];
  const batchDone = () => { selected.slice(0, 50).forEach((id) => { const todo = todos.find((item) => item.id === id); if (todo) completeTodo(todo); }); setSelected([]); setBatchOpen(false); };
  return <><PageHeader productReference={productRef('growth.todo.overview')} title="待办事项" action={<span data-product-ref={productRef('growth.todo.interaction')}><Button type="primary" icon={<Plus size={15} />} onClick={() => setDrawer({ kind: 'todo' })}>新建待办</Button></span>} />
    <div data-product-ref={productRef('growth.todo.interaction')}><Card><Flex className={styles.todoToolbar} justify="space-between" wrap="wrap" gap={12}><Tabs activeKey={tab} onChange={setTab} items={[{ key: 'today', label: '今日' }, { key: 'week', label: '本周' }, { key: 'calendar', label: '日历' }, { key: 'all', label: '全部' }, { key: 'statistics', label: '统计' }]} /><Space><Select value={filter} style={{ width: 120 }} options={[{ value: 'all', label: '全部状态' }, ...['todo', 'in_progress', 'done', 'abandoned'].map((value) => ({ value, label: statusLabel(value) }))]} onChange={(value) => setFilter(value as TodoStatus | 'all')} />{selected.length > 0 && <Button onClick={() => setBatchOpen(true)}>批量完成 {selected.length}</Button>}</Space></Flex>
      {tab === 'calendar' && <Alert type="info" showIcon title={`七月排程：${todos.filter((todo) => todo.planned.startsWith('2026-07')).map((todo) => `${todo.planned.slice(-2)} 日 ${todo.title}`).join(' · ') || '暂无本月待办'}`} />}
      {tab === 'statistics' ? <div data-product-ref={productRef('growth.todo.metrics')}><TodoStatistics todos={todos} /></div> : <Table rowKey="id" dataSource={visible} columns={columns} pagination={false} />}
    </Card></div><div data-product-ref={productRef('growth.todo.interaction')}><Card className={styles.sectionRow} title="周期模板" extra={<Tag color="purple">完成后生成下一条</Tag>}>{templates.length ? <Flex vertical className={styles.templateList} gap={12}>{templates.map((template) => <Flex key={template.id} justify="space-between" align="center"><div><b>{template.base.title}</b><small>{repeatLabel(template.rule)}</small></div><Switch checked={template.active} checkedChildren="运行" unCheckedChildren="暂停" onChange={(active) => setTemplates((items) => items.map((item) => item.id === template.id ? { ...item, active } : item))} /></Flex>)}</Flex> : <Alert type="info" showIcon title="暂无周期待办模板，可通过“新建待办”的周期执行区块创建。" />}</Card></div>
    <Modal title="批量完成待办" open={batchOpen} onOk={batchDone} onCancel={() => setBatchOpen(false)} okText="确认完成" cancelText="取消"><div data-product-ref={productRef('growth.todo.interaction')}><p>将完成已选择的 {Math.min(selected.length, 50)} 条待办。周期待办会按各自规则生成下一条实例。</p>{selected.length > 50 && <Alert type="warning" showIcon title="单次最多操作 50 条，仅处理前 50 条。" />}</div></Modal>
  </>;
}
function TodoStatistics({ todos }: { todos: Todo[] }) { const completed = todos.filter((todo) => todo.status === 'done').length; return <Row gutter={[16, 16]} className={styles.statistics}><Col xs={24} md={8}><Statistic title="完成率" value={Math.round((completed / Math.max(1, todos.length)) * 100)} suffix="%" /></Col><Col xs={24} md={8}><Statistic title="逾期待办" value={todos.filter((todo) => todo.due < TODAY && todo.status !== 'done').length} suffix="项" /></Col><Col xs={24} md={8}><Statistic title="第一象限" value={todos.filter((todo) => todo.importance >= 4 && todo.urgency >= 4).length} suffix="项" /></Col></Row>; }
