import type { WebMappingRule, WebMappingRules } from "./types.ts";

const directComponentTypes = [
  "Alert",
  "Anchor",
  "AutoComplete",
  "Avatar",
  "Badge",
  "Breadcrumb",
  "Button",
  "Calendar",
  "Card",
  "Carousel",
  "Cascader",
  "Checkbox",
  "Collapse",
  "ColorPicker",
  "DatePicker",
  "Descriptions",
  "Divider",
  "Dropdown",
  "Empty",
  "Flex",
  "FloatButton",
  "Form",
  "Image",
  "Input",
  "InputNumber",
  "Layout",
  "Masonry",
  "Mentions",
  "Menu",
  "Modal",
  "Pagination",
  "Popconfirm",
  "Popover",
  "Progress",
  "QRCode",
  "Radio",
  "Rate",
  "Segmented",
  "Skeleton",
  "Slider",
  "Space",
  "Spin",
  "Splitter",
  "Statistic",
  "Switch",
  "Table",
  "Tabs",
  "Tag",
  "Timeline",
  "TimePicker",
  "Tooltip",
  "Tour",
  "Transfer",
  "Tree",
  "TreeSelect",
  "EditableText",
  "Upload",
  "Watermark",
] as const;

const componentRuleOverrides: Partial<
  Record<(typeof directComponentTypes)[number], Pick<WebMappingRule, "aliases" | "props" | "events" | "notes">>
> = {
  Segmented: {
    aliases: ["RadioButtonGroup"],
    props: {
      value: "Bind the current mutually exclusive selection to a stable value.",
      options: "Build dynamic choices as { label, value } objects. Keep option value types consistent with business state.",
    },
    events: {
      change: "Map the selected value back to business state, then run the existing filter behavior.",
    },
    notes: "Map the Figma semantic `RadioButtonGroup` to Segmented for compact mutually exclusive category controls. Use Radio only when the design is a conventional form-field radio group.",
  },
  Tabs: {
    aliases: ["tabs"],
    props: {
      activeKey: "Bind the current top-level selection to a stable key. Use a stable internal sentinel for an \"all\" option when the business value is empty.",
      items: "Build dynamic tabs as { key, label } objects. Dynamic labels do not require a manual button implementation.",
      tabBarExtraContent: "Place aligned controls such as search in the tab bar's extra-content API when the design puts them beside tabs.",
    },
    events: {
      change: "Map the selected key back to business state, then run the existing filter behavior.",
    },
    notes: "Map Figma node names `Tabs` and `tabs` to Tabs. Check the component docs before using manual buttons; dynamic options and controlled filtering are supported use cases.",
  },
};

const directRules = directComponentTypes.map((componentType) => ({
  componentType,
  importSource: "@sue/design-web-vue",
  importName: componentType,
  renderStrategy: "component",
  props: {},
  slots: {},
  events: {},
  ...componentRuleOverrides[componentType],
} as const));

export const webMappingRules = {
  target: "vue3-tsx",
  rules: [
    ...directRules,
    {
      componentType: "Select",
      importSource: "@sue/design-web-vue",
      importName: "Select",
      renderStrategy: "component",
      props: {
        value: "Bind the current selection value. For single select this is usually a string or number; multiple/tags use arrays; labelInValue uses labeled objects.",
        options: "Map stable option arrays to { label, value } objects. Keep option value types consistent with the business state.",
        placeholder: "Map placeholder text directly to Select.placeholder.",
        prefix: "Use prefix for fixed leading text or icon inside the selector instead of rendering an external label wrapper.",
        suffixIcon: "Use suffixIcon or the suffixIcon slot only when the design requires a custom dropdown icon.",
      },
      slots: {
        prefix: "Use #prefix for custom leading nodes inside Select.",
        suffixIcon: "Use #suffixIcon for custom dropdown icons.",
      },
      events: {
        "update:value": "In TSX, do not annotate the callback parameter as a business enum or DTO field type. Let the component value infer, narrow by runtime shape, then pass it to business state. Example: onUpdate:value={(value) => { if (typeof value === 'string') setSelectedType(value as BusinessType) }}.",
      },
      notes: "When a design shows fixed leading text or an icon plus selectable content, still render a single Select with prefix/#prefix. Do not build an outer label container around Select. If allowClear, mode=\"multiple\", or labelInValue is used, narrow undefined, arrays, or labeled values before calling business setters.",
    },
    {
      componentType: "Drawer",
      importSource: "@sue/design-web-vue",
      importName: "Drawer",
      renderStrategy: "component",
      props: {
        open: "Control drawer visibility; support v-model:open in templates.",
        title: "Map drawer title text to Drawer.title or #title.",
        closable: "Close button defaults to header end (top-right). Use { placement: 'start' } only when the design requires close before the title.",
        extra: "Use #extra only for header-corner actions. Do not put bottom action areas here.",
        size: "Map design width to size (number, 'default', or 'large').",
        placement: "Map slide direction to placement: left | right | top | bottom.",
        loading: "Use only when the design explicitly shows skeleton in the drawer body.",
      },
      slots: {
        default: "Drawer body content. Body has no default padding — apply padding on inner containers.",
        extra: "Header-corner actions only (not bottom action areas).",
        title: "Custom title node when title prop is not enough.",
      },
      events: {
        close: "Handle drawer close from mask, close button, or ESC.",
        "update:open": "Sync open state when using v-model:open.",
      },
      notes: "Drawer has no footer slot. When the design shows a bottom action area, render Flex vertical container=\"full\" inside #default: fill region scrolls (add padding on the fill container), fixed region at the bottom holds actions — map controls per design (Button, ButtonGroup, Space, etc.). Do not use footer prop/slot, #extra for bottom actions, or paddingBottom hacks. For toolbar + table inside drawer, nest fixed + fill within the fill region. See layout-flex scenario and demo/drawer-bottom-actions.md.",
    },
    {
      componentType: "Grid",
      importSource: "@sue/design-web-vue",
      importName: "Row",
      renderStrategy: "component",
      props: {
        children: "Render layout children with Row and Col.",
        gutter: "Map spacing or layout gap to Row gutter.",
      },
      slots: {
        default: "Use Row children; wrap child nodes in Col when column spans are known.",
      },
      events: {},
      notes: "Grid is implemented by Row/Col exports in @sue/design-web-vue.",
    },
    {
      componentType: "Message",
      importSource: "@sue/design-web-vue",
      importName: "message",
      renderStrategy: "service",
      props: {
        type: "Map to message.success/info/warning/error/loading.",
        content: "Map semantic message text to service content.",
      },
      slots: {},
      events: {},
      notes: "Message is a service API, not a JSX component.",
    },
    {
      componentType: "Notification",
      importSource: "@sue/design-web-vue",
      importName: "notification",
      renderStrategy: "service",
      props: {
        type: "Map to notification.success/info/warning/error.",
        message: "Map semantic title to notification message.",
        description: "Map semantic body text to notification description.",
      },
      slots: {},
      events: {},
      notes: "Notification is a service API, not a JSX component.",
    },
    {
      componentType: "List",
      importSource: "@sue/design-web-vue",
      importName: null,
      renderStrategy: "manual",
      props: {
        dataSource: "Render list data with semantic HTML, Space, Card, Empty, Pagination, or Table depending on density.",
        renderItem: "Map item rendering to a local TSX render function.",
        pagination: "Render Pagination separately when needed.",
      },
      slots: {
        default: "Render item rows/cards manually.",
      },
      events: {},
      notes: "List is in design-spec but is not exported by @sue/design-web-vue yet.",
    },
  ],
} satisfies WebMappingRules;
